#
#
#   ██████╗ ██████╗ ██╗   ██╗███╗   ███╗███████╗     █████╗ ██████╗ ██╗
#  ██╔═══██╗██╔══██╗██║   ██║████╗ ████║██╔════╝    ██╔══██╗██╔══██╗██║
#  ██║   ██║██████╔╝██║   ██║██╔████╔██║█████╗      ███████║██████╔╝██║
#  ██║   ██║██╔══██╗██║   ██║██║╚██╔╝██║██╔══╝      ██╔══██║██╔═══╝ ██║
#  ╚██████╔╝██║  ██║╚██████╔╝██║ ╚═╝ ██║███████╗    ██║  ██║██║     ██║
#   ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝    ╚═╝  ╚═╝╚═╝     ╚═╝
#
# Docs: https://docs.orume.id/documentations/orume-api/introduction
# Copyright (c) 2022 - Orume Studios
licenseKey: "hohoho"
system:
  cronSchedule: ""
  dataPath: "./data"
  orumeApi:
    configFile: "./config.yml"
    systemPort: 20202
  database:
    dialect: "mysql"
    localPath: "test.sq"
    param: "charset=utf8&parseTime=true"
    credentials:
      username: "YOUR_DATABASE_USERNAME"
      password: "YOUR_DATABASE_PASSWORD"
      host: "YOUR_DATABASE_HOST"
      port: "YOUR_DATABASE_PORT"
      databaseName: "YOUR_DATABASE_NAME"
    gormConfig:
      skipDefaultTransaction: false
      fullSaveAssociations: false
      dryRun: false
      prepareStmt: false
      disableAutomaticPing: false
      disableForeignKeyConstraintWhenMigrating: false
      disableNestedTransaction: false
      allowGlobalUpdate: false
      queryFields: false
      createBatchSize: 1024
      logger: true
  authentication:
    defaultUser:
      username: admin
      password: YOUR_ADMIN_PASSWORD
    sessionTime: 300
    secretKey: YOUR_SECRET_KEY
    encryptionKey: YOUR_ENCRYPTION_KEY
modules:
  license:
    enable: true
    modelName: license_models
    path: /license
  wallet:
    enable: true
middlewares:
  underAttack:
    enable: false
    maxConnections: 1000
    timeRemoval: 1
  rateLimit:
    enable: false
    whitelistedIps: ["127.0.0.1"]
    maxIpAddresses: 1000
    limits:
      second:
        enable: true
        maxRequest: 10
        coolDown: 120
      minute:
        enable: true
        maxRequest: 50
        coolDown: 20
      hour:
        enable: false
        maxRequest: 10
        coolDown: 10
      day:
        enable: false
        maxRequest: 10
        coolDown: 10
  userAgent:
    all:
      enable: false
      enableOnUnderAttack: false
      userAgents: ["PostmanRuntime/7.29.0"]
    admin:
      enable: false
      userAgents: ["PostmanRuntime/7.29.0"]
  ipWhitelist:
    all:
      enable: false
      enableOnUnderAttack: true
      whitelistedIps:
        - "118.99.110.226"
    admin:
      enable: false
      whitelistedIps:
        - '::1'
  logger:
    enable: true
